# Site configuration for the Chirpy preview

theme: jekyll-theme-chirpy

lang: fa-IR
timezone: Asia/Tehran

title: Let's DIY
tagline: تجربه‌های شخصی در برنامه‌نویسی، الکترونیک و پروژه‌های DIY
description: >-
  تجربه‌های شخصی من درباره پروژه‌های دات‌نت، سیستم‌های الکترونیکی، اینترنت اشیا و پروژه‌های DIY

url: "https://letsdiy.ir"
baseurl: ""

github:
  username: AlirezaSabouei

social:
  name: Alireza Sabouei
  links:
    - https://github.com/AlirezaSabouei
    - https://www.linkedin.com/in/alireza-sabouei/

toc: true

theme_mode:

paginate: 10

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      comments: false
      permalink: /posts/:title/

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - README.md
  - LICENSE
  - "*.gem"
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
