title: Let's DIY
theme: minima

author: Alireza Sabouei (علیرضا صبوئی)

description: >
  تجربه های شخصی من درباره پروژه های دات نت، سیستم های الکترونیکی و اینترنت اشیا و پروژه های DIY

show_excerpts: true
hide_site_feed_link: true
excerpt_separator: <!--بیشتر-->